services:
  web:
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/
      - ./html:/usr/share/nginx/html/
      - ./logs:/var/log/nginx/
      - ./ssl:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
